services:
  database:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: xxxx
      MYSQL_DATABASE: xxxx
      MYSQL_USER: xxxx
      MYSQL_PASSWORD: xxxx
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s
    expose:
      - "3306"

  cache:
    image: redis:6-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    expose:
      - "6379"

  socket:
    image: socketcluster/socketcluster:v17.4.0
    restart: unless-stopped
    environment:
      SOCKETCLUSTER_WORKERS: 4
      SOCKETCLUSTER_BROKERS: 4
    expose:
      - "8000"

  application:
    image: fleetbase/fleetbase-api:latest
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      APP_NAME: Mora
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: base64:xxxx
      APP_URL: https://api.xxxx.com
      LOG_CHANNEL: daily
      CONSOLE_HOST: https://xxxx.xxxx.com
      FRONTEND_HOSTS: https://xxxx.xxxx.com

      # maps
      MAPS_VENDOR: mapbox
      MAPBOX_ACCESS_TOKEN: xxxxx
      # Optional tuning
      MAPBOX_DIRECTIONS_PROFILE: driving
      MAPBOX_MATRIX_PROFILE: driving
      MAPBOX_COUNTRY_BIAS: NG

      # ---- DB (internal) ----
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: xxxx
      DB_USERNAME: xxxx
      DB_PASSWORD: xxxxx

      # Use same DB for storefront
      STOREFRONT_DB_CONNECTION: mysql
      DB_STOREFRONT_HOST: database
      DB_STOREFRONT_PORT: 3306
      DB_STOREFRONT_DATABASE: xxxx
      DB_STOREFRONT_USERNAME: xxxx
      DB_STOREFRONT_PASSWORD: xxxxx

      # ---- Redis/queue ----
      QUEUE_CONNECTION: redis
      CACHE_DRIVER: redis
      REDIS_CLIENT: phpredis
      REDIS_HOST: cache
      REDIS_PORT: 6379
      CACHE_URL: redis://cache:6379
      REDIS_URL: redis://cache:6379

      # Auth/cookies across subdomains
      SESSION_DOMAIN: .xxxx.com
      SESSION_SECURE_COOKIE: "true"
      SESSION_SAME_SITE: none
      SANCTUM_STATEFUL_DOMAINS: xxxx.xxxx.com
      TRUSTED_PROXIES: "*"
      
      # Safe mail default so flows never 500 on SMTP
      # MAIL_MAILER: smtp
      # MAIL_HOST: smtp.xxxx.org
      # MAIL_PORT: 587
      # MAIL_ENCRYPTION: tls
      # MAIL_USERNAME: "xxxxx@xxxx.com"
      # MAIL_PASSWORD: "xxxxx"
      # MAIL_FROM_ADDRESS: "xxxx@xxxx.com"
      # MAIL_FROM_NAME: "Parceli"

      # MAIL_MAILER: smtp
      # MAIL_HOST=: smtp.xxxx.com
      # MAIL_PORT: 587
      # MAIL_USERNAME: xxxx@xxxx.com
      # MAIL_PASSWORD: xxxx
      # MAIL_ENCRYPTION: tls
      # MAIL_FROM_ADDRESS: xxxx@xxxx.com
      # MAIL_FROM_NAME: "Mora Logistics"

      #SMS
      # TWILIO_SID: xxxxx
      # TWILIO_TOKEN: xxxx
      # TWILIO_FROM: "+xxxx"

      # file system
      # FILESYSTEM_DISK: public

      # Optional defaults
      BROADCAST_DRIVER: socketcluster
      REGISTRY_HOST: https://registry.fleetbase.io
      REGISTRY_PREINSTALLED_EXTENSIONS: "true"
      OSRM_HOST: https://router.project-osrm.org

      # allow your console origin
      CORS_ALLOWED_ORIGINS: https://console.moralogistics.com
    expose:
      - "8000"

  queue:
    image: fleetbase/fleetbase-api:latest
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    command: ["php","artisan","queue:work","--tries=3","--timeout=90"]
    environment:
      APP_KEY: base64:xxxx
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: xxxxx
      DB_USERNAME: xxxx
      DB_PASSWORD: xxxx
      QUEUE_CONNECTION: redis
      REDIS_HOST: cache
      REDIS_PORT: 6379
    healthcheck:
      test: ["CMD-SHELL", "php -r 'exit((getenv(\"APP_KEY\") && extension_loaded(\"pdo_mysql\"))?0:1);'"]
      interval: 30s
      timeout: 5s
      retries: 5

  scheduler:
    image: fleetbase/fleetbase-api:latest
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    command: ["go-crond","--verbose","root:./crontab"]
    environment:
      APP_KEY: base64:xxxxx
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: xxxx
      DB_USERNAME: xxxx
      DB_PASSWORD: xxxx
      QUEUE_CONNECTION: redis
      REDIS_HOST: cache
      REDIS_PORT: 6379
    healthcheck:
      test: ["CMD-SHELL", "php -r 'exit((getenv(\"APP_KEY\") && extension_loaded(\"pdo_mysql\"))?0:1);'"]
      interval: 30s
      timeout: 5s
      retries: 5

  console:
    image: fleetbase/fleetbase-console:latest
    restart: unless-stopped
    environment:
      MAPS_PROVIDER: mapbox
      MAPBOX_TOKEN: xxxxxx
    volumes:
      - ./console/fleetbase.config.json:/usr/share/nginx/html/fleetbase.config.json:ro
    expose:
      - "4200"

  phpmyadmin:
    image: phpmyadmin:5-apache
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
    expose:
      - "80"

  caddy:
    image: caddy:2
    restart: unless-stopped
    depends_on:
      application:
        condition: service_started
      console:
        condition: service_started
      socket:
        condition: service_started
      phpmyadmin:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.edge:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

volumes:
  caddy-data:
  caddy-config:
  mysql-data: